### ISSUE TITLE
mako 15.1 jars do not appear to be signed

### ISSUE THREAD

**Issue by rlbdv** [lineageos4microg/l4m_website#21] opened 2018-06-10 18:15 UTC
e.g. from https://download.lineage.microg.org/mako/

```sh
$ keytool -list -printcert -jarfile lineage-15.1-20180604-microG-mako.zip
Not a signed jar file
```

but the 14.1 image is signed:

```sh
$ keytool -list -printcert -jarfile lineage-14.1-20180427-microG-mako.zip
Signer #1:
...
```

But the 14.1 image there, `https://download.lineage.microg.org/mako/lineage-14.1-20180427-microG-mako.zip` is signed.

**Comment by corna** [comment] 2018-06-23 08:44
Duplicate of lineageos4microg/docker-lineage-cicd#4

**Closed by corna** 2018-06-23 08:44 UTC

**Comment by dontub** [comment] 2018-08-04 13:49
IMHO this should be reopened since the website has to be updated to explain how to verify the new signature format.

**Comment by rugk** [comment] 2020-11-02 15:19
This seems to be tracked in https://github.com/lineageos4microg/l4m_website/issues/58 now.
