### ISSUE TITLE
Update website to explain new sig checking technique

### ISSUE THREAD

**Issue by alxpettit** [lineageos4microg/l4m_website#25] opened 2018-11-29 20:31 UTC
#### Update:

The correct way to check build signatures has been explained in the comments below, however, the website still does not contain any up-to-date information on this. Please update the website to explain it!

---
#### Original post:

I just pulled `lineage-15.1-20181126-microG-bullhead.zip`, tried to verify per the instructions, and it didn't work. (`keytool -list -printcert -jarfile [file]`)

It's notable that this method of checking sigs has not worked on lineageOS's official releases either for a long time -- they are now using a [different signature checking mechanism, against all common sense](https://github.com/LineageOS/update_verifier). Oddly enough, they have *still* not updated their documentation to reflect this.

Anyway, can anyone tell me what's up with this?

**Comment by alxpettit** [comment] 2018-11-30 10:41
@rugk Why was that issue closed? It hasn't been solved.

**Comment by rugk** [comment] 2018-11-30 20:04
Because you know need to use a different method for verifying the ZIPs now. Read through https://github.com/lineageos4microg/docker-lineage-cicd/issues/4 for more information.

**Comment by alxpettit** [comment] 2018-11-30 21:44
@rugk  Why hasn't the website's instructions been updated?

**Comment by rugk** [comment] 2018-11-30 21:47
Well… that's a thing that needs to be done. :smile:

**Comment by rugk** [comment] 2018-11-30 21:49
BTW also see https://github.com/lineageos4microg/docker-lineage-cicd/issues/24, and https://github.com/lineageos4microg/docker-lineage-cicd/issues/21 is likely also a dupe of this…

**Comment by alxpettit** [comment] 2018-11-30 21:51
@rugk No worries, I updated the issue title. It's now here to track the fact that this section of the website has not been updated. :stuck_out_tongue_closed_eyes:

**Comment by corna** [comment] 2018-12-01 10:57
Sorry for the delay, I'll try to do it this weekend ;)

**Comment by corna** [comment] 2018-12-02 17:49
Done in 61d526e9d337fbb11d6cacbd7fb51bb7f3df9110

**Closed by corna** 2018-12-02 17:49 UTC
